### ISSUE TITLE
公式(7)与代码实现疑问？

### ISSUE THREAD

**Issue by sanyu6** [Scottdyt/HAKG#3]
你好，我注意到你在庞加莱圆盘模型上计算实体embedding时，论文中公式是:
![image](https://user-images.githubusercontent.com/96935888/178933733-f426e101-8eec-4d02-993e-b97fb008b8b9.png)
这里说明embedding是在圆盘上面的，而你代码上面:
![image](https://user-images.githubusercontent.com/96935888/178933929-82e8329a-5cc6-4cc4-a7e2-50e5cd7699fc.png)
我直观上理解为: 每次计算时都将嵌入先投影到圆盘模型上面，然后进行Mobius addition，再投回切空间进行聚合，这样的话其实实体embedding结果不应该还是在切空间吗?这样和论文里的公式是不是有点不符合

**Comment by yuntaod** [comment]
Hi SunYu,

We map the embedding into the hyperbolic space for Mobius addition (context aggregation), and then map back them into tangent space for optimization. We describle our optimization details in sec 4.1.4. 

In fact, you are free to choose to initialize the embeddings in Eculidean space or hyperbolic space. Due to the precision issue, the performance can be different a little bit (but very marginal). You can try it on with hyperbolic optimization technique, 
like Riemannian SGD.

**Comment by sanyu6** [comment]
thanks
